### ISSUE TITLE
Idea: Autoinstall wls and deb

### ISSUE THREAD

**Issue by LEv145** [P2Enjoy/kohya_ss-docker#10]
It would be useful to use!

And especially since download sources are sometimes hard to find:

<details>
  <summary>Spoiler</summary>
  
  ![изображение](https://user-images.githubusercontent.com/40071054/224515546-be9014da-4548-4219-94f6-2372aad91c35.png)
  ![изображение](https://user-images.githubusercontent.com/40071054/224515565-bcf83a28-d2c5-44dc-b7c2-e208ee68f076.png)
  and
  ![изображение](https://user-images.githubusercontent.com/40071054/224515613-2103a52a-4b5a-4c2c-96de-e2417c78e1fe.png)
  ![изображение](https://user-images.githubusercontent.com/40071054/224515582-f99ab4c0-de59-4bea-a326-3f905e68ec45.png)
</details>

This can be done either by simply injecting this feature into the `Dockerfile` or by the method from https://github.com/AbdBarho/stable-diffusion-webui-docker with `download` profile:
https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/docker-compose.yml#L21-L25
https://github.com/AbdBarho/stable-diffusion-webui-docker/tree/master/services/download

Сan use **[conda](https://docs.conda.io/en/latest/)(recommend to try)** or [pythonhosted](https://files.pythonhosted.org/packages/)
Сan also add automatic compilation of the necessary files

**Comment by martinobettucci** [comment]
The real problem with this are the licence of these files @LEv145.
I know people do this stuff online but this is not exactly legal compliant.
Unfortunately NVIDIA libraries cannot be installed or distributed automatically following their licence because one should be a registered NVidia developers to download and use them.
Although we can autoinstall and link the open source xformers libraries, we have to leave you to manually download the NVidia binaries.
"Good" news, the NVidia libraries are OPTIONAL and the repository can be operated without (but it will be slower).

Concerning the versions, xformer is built from source on our servers so we link with 0.0.17 which is built from the git repository. You can use the 0.0.16 just fine :)

**Comment by LEv145** [comment]
> 

No need to distribute files
It seems to me that downloading files from open sources such as conda does not violate the license. The script itself will not violate the license, but maybe the one who runs it will

Can even make a script that requires registration and use the nvidia api

**Comment by LEv145** [comment]
Сan also make an auto-installation, where sources need to be entered manually (which is what torrent clients do)

**Comment by martinobettucci** [comment]
Hey @LEv145, excellent suggestion!

Feel free to make a PR :-)
