### ISSUE TITLE
WARN[0000] The "DISPLAY" variable is not set. Defaulting to a blank string. 

### ISSUE THREAD

**Issue by KingWu** [P2Enjoy/kohya_ss-docker#17]
What value should be set on DISPLAY?

**Comment by martinobettucci** [comment]
Maybe you're not running an X server.
If you don't, it is not a big deal: you might have to put the folders manually instead of using the folder selector (as this window rely on the X display to show).

You can find your DISPLAY value by opening à shell and ` echo $DISPLAY` or by using this command if SSH 
```
SESSION=$(loginctl show-user "$USER" --property Sessions --value)
DISPLAY=$(loginctl show-session $SESSION --property Display --value)

echo "$DISPLAY"
```

If case nothing shows, you're probably on WAYNE (instead of X) thus the previous WARN (which is not an error per se)
Cheers!
