### ISSUE TITLE
Runpod.io

### ISSUE THREAD

**Issue by ipechman** [P2Enjoy/kohya_ss-docker#3]
Can't seem to make it run with runpod.io

**Comment by derto42** [comment]
Did you make this work?

**Comment by martinobettucci** [comment]
Perhaps if someone tell me what should I do to help with Runpod? @ipechman @derto42 I'll be happy to help

**Comment by ipechman** [comment]
> Did you make this work?

Nope

**Comment by derto42** [comment]
> Perhaps if someone tell me what should I do to help with Runpod? @ipechman @derto42 I'll be happy to help

Just wasn't sure how to run docker stuff on runpod. 

Ended up finding this instead, worked flawlessly: https://github.com/Thund3rPat/kohya_ss-linux.git

I think the problem is the fact that it is docker,

**Comment by ipechman** [comment]
Thanks for letting me know! Even the gui worked with runpod?

**Comment by derto42** [comment]
> Thanks for letting me know! Even the gui worked with runpod?

Yeah! Use the desktop template. Set the Disk volume to 30 GB

Then set everything up using these commands:

sudo -s
git clone https://github.com/Thund3rPat/kohya_ss-linux.git
cd kohya_ss-linux
python3 -m venv venv
source venv/bin/activate
pip install --use-pep517 --upgrade -r requirements.txt
apt-get update
apt-get install python3-tk


Then after everything is set up, make a new terminal instance in the kohya folder, 

Run this command:

xhost +

This will allow the GUI to work.


Sometimes it gives me an error:
The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
Aborted (core dumped)

If that happens, I usually just restarted the setup and did everything line by line instead of pasting everything in at once.

**Comment by derto42** [comment]
> Thanks for letting me know! Even the gui worked with runpod?

Please let me know if that works, Been working on this for the past 3-4 days, want to make sure what I did is re-creatable by others.

**Comment by ipechman** [comment]
Thank you! I'll let you know when I give it a try

**Comment by derto42** [comment]
Update: I am able to set everything up but I trains corrupted LORAs

**Comment by martinobettucci** [comment]
If you train corrupted LoRA it may be because your SD is loading in another cast (fp16 when the safetensors are fp32 or videversa)

**Comment by derto42** [comment]
> If you train corrupted LoRA it may be because your SD is loading in another cast (fp16 when the safetensors are fp32 or videversa)

how do I fix something like this? I used a google colab with kohya and trained it with fp16, the resulting lora worked fine with the model I was using to test. When doing the same through the Linux version, the output was corrupted. both were trained using fp16 in the settings and tested using the same model.

**Comment by martinobettucci** [comment]
I should have to look into your configuration... can't help with a comment on github: sorry :-(
If you need professionally made LoRA you can go for my services: https://www.fiverr.com/share/P6dp5G (5 stars ratings so far)
